### ISSUE TITLE
Cannot use standard RNG in Blockchain Runtime

### ISSUE THREAD

**Issue by shawntabrizi** [athei/substrate-schellingcomp#1]
https://github.com/athei/substrate-schellingcomp/blob/84b09baabf9a031b8cf218c3ba12809665515c22/runtime/src/schellingcomp.rs#L45

TBH I did not look very deeply into exactly how you were using the RNG libraries here, but in general, you cannot use standard RNG methods on the blockchain because they are not deterministic, and multiple nodes running the same code will not come to consensus about the outcome.

Instead you should use the on-chain random seed generated using the deterministic (yet hard to influence) mixing algorithm:
https://github.com/shawntabrizi/substrate-collectables-workshop/blob/master/2/generating-random-data.md

**Comment by athei** [comment]
Hey thanks for the feedback.

I seed the SmallRng (which is a prng) from the deterministic seed you mentioned:
https://github.com/athei/substrate-schellingcomp/blob/84b09baabf9a031b8cf218c3ba12809665515c22/runtime/src/schellingcomp.rs#L201-L214

Therefore the prng yields the same sequence of random numbers for each node as far as I understand it. This would only be indeterministic if the seed is indeterminstic for example if you take it from` /dev/urandom`.

I also add that in my opinion we do not need a cryptographically secure prng here because the seed is public anyways.

This should okay as an on-chain code, right?

**Comment by shawntabrizi** [comment]
Seems reasonable, but why jump through all the hoops and add additional libraries (bloat) to the runtime when you can simply hash the seed and turn that into a random number to select from the AvailableClientArray?

Anyway, your flavor of random number generation is less important than your understanding of correctly using the on-chain seed to seed the rng libraries. :)

cool project 👍

**Comment by athei** [comment]
> Seems reasonable, but why jump through all the hoops and add additional libraries (bloat) to the runtime when you can simply hash the seed and turn that into a random number to select from the AvailableClientArray?

Because I need not one but ``n`` random numbers with a uniform distribution. This seemed to be the best way to do this. Maybe I am missing something?
 
> cool project 👍

Thanks :)
